import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainRoot({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
        <AppSidebar />
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <SidebarTrigger />
            {children}
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
