import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css"; 

export const metadata: Metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function MainRoot({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}