import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { Manrope } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const manrope = Manrope({
  subsets: ["latin"], 
  weight: ["400", "600", "700"], 
  variable: "--font-manrope", 
});

export default function MainRoot({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className="font-manrope">
            <Header/>
            {children}
            <Footer/>
      </body>
    </html>
  );
}
